# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# global settings
title: "jsdnhk@github profile"
email: "dn@jsdnhk.com"
description: "jsdnhk@github profile - 2019"
# url: "https://jsdn.hk"
github: [metadata]
github_username: "jsdnhk"
repository: "jsdnhk/jsdnhk.github.io"
theme: "jekyll-theme-midnight"
analytics_account: "UA-3769691-28" # for google analytics

# build settings
exclude: ["etc", "scripts", "vendor", "Gemfile", "Gemfile.lock", "Rakefile", "README.md", "package.json", "node_modules"]
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
#  - jekyll-include-cache

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/
