# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# global settings
title: "jsdn.hk"
email: "dn@jsdn.hk"
description: "Simple Note"
keywords: "about-me, personal-blog, quotes, contacts, geek, main-page, useful-links, hker"
tagline: "Simple Note"
url: "https://jsdn.hk"
language: en
github: [metadata]
github_url: "https://github.com/"
github_username: "jsdnhk"
repository: "jsdnhk/jsdnhk.github.io"
timezone: "Asia/Hong_Kong"
google_analytics_account: "UA-141729733-1"
disqus_shortname: jsdnhk

# not use default theme
# location: /var/lib/gems/2.5.0/gems/jekyll-theme-midnight-0.1.1
# theme: "jekyll-theme-midnight"

# build settings
collections_dir: collections
exclude:
  - "etc"
  - "scripts"
  - "logs"
  - "vendor"
  - "Gemfile*"
  - "package.json*"
  - "Rakefile"
  - "rakelib"
  - "node_modules"
  - ".idea"
  - ".github"
  - "**/*/node_modules"
  - "**/*/package.json*"
profile: true
strict_front_matter: true

# enable GFM
kramdown:
  input: GFM
  hard_wrap: false
  math_engine_opts:
    preview: true
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions

# default permalink is assigned to the posts
blog_baseurl: "/blog/"
permalink: /blog/:year:month:day

# front matter defaults settings
excerpt_separator: "<!--end-->"
defaults:
  # collections
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
      title:
      title_image:
      title_display: false
      footer_quote:
      sitenav:
      tags:
      categories:
  - scope:
      path: "*.md"
      type: "pages"
    values:
      layout: page_md
  # posts
  - scope:
      path: "collections/_posts"
      type: "posts"
    values:
      layout: post
      tags: []
      category: ""
      display: true
      comment: false
  - scope:
      path: "collections/_posts/test"
      type: "posts"
    values:
      display: false
  # assets
  - scope:
      path: "assets/videos/bg"
    values:
      video_bg: true

# site-scope variables
path_header_image:
  h1: "/assets/images/oxygen/48x48/"
  h2: "/assets/images/oxygen/48x48/"
  h3: "/assets/images/oxygen/32x32/"
  h4: "/assets/images/oxygen/32x32/"
  h5: "/assets/images/oxygen/22x22/"
  h6: "/assets/images/oxygen/22x22/"