#!/bin/sh

set -e

scripts/branding

export PATH=/usr/share/rbenv/shims:$PATH RBENV_VERSION=$(cat .ruby-version)

bundle exec rake test
bundle exec rubocop -D -S

# Ensure the Code for America and Code for All list only contain official chapters/partners
# Disabled for now due to false positives
# bundle exec scripts/fetch-cfa

# Ensure only organizations are listed
bundle exec scripts/ensure-orgs

# Ensure all organizations are listed only once
bundle exec scripts/ensure-unique
