---
name: "Auditing"
on:
  push:
    branches:
      - master
jobs:
  lighthouse-stdout:
    runs-on: ubuntu-latest
    steps:
      - name: "mainpage performance"
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://jsdn.hk'
      - name: "resume performance"
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://jsdn.hk/resume'
      - name: "blog performance"
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://jsdn.hk/blog'
      - name: "quotes performance"
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://jsdn.hk/quotes'
      - name: "links performance"
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://jsdn.hk/links'
      - name: "toolset performance"
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://jsdn.hk/toolset'
      - name: "fonts performance"
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://jsdn.hk/fonts'
      - name: "Upload results as an artifact"
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-report
          path: './report'